### ISSUE TITLE
Azure regions?

### ISSUE THREAD

**Issue by TyNev** [MicrosoftDocs/industry-solutions#2]
This article refers generically to the geographic regions that the cloud for healthcare is available in, but the question my team is trying to answer is which **Azure regions** (https://docs.microsoft.com/en-us/azure/virtual-machines/regions) it is available in. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9235f816-8ba2-764c-8c45-8a66d8d08582
* Version Independent ID: df689ddb-f17d-b56e-6775-96a6d2352c9d
* Content: [International availability of Microsoft Cloud for Healthcare](https://docs.microsoft.com/en-us/industry/healthcare/availability)
* Content Source: [industry-solutions/healthcare/availability.md](https://github.com/MicrosoftDocs/industry-solutions-pr/blob/live/industry-solutions/healthcare/availability.md)
* Service: **industry**
* Sub-service: **healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by TyNev** [comment]
Re-read article, it appears to have a link to power platform docs that might cover this question.

**Comment by TyNev** [comment]
Reviewed linked content, does not even remotely answer the question. The linked PDF does not mention Azure Cloud for Healthcare at all.

**Comment by andreabichsel** [comment]
Hi @TyNev, a SME responded, "Availability of Teams and Dynamics services does not map to Azure regions. Furthermore, the service level agreement for some services states that to provide high availability the location of a data center might change at any time."
