### ISSUE TITLE
Link to pricing guide does not work

### ISSUE THREAD

**Issue by MichalKolb1** [MicrosoftDocs/industry-solutions#32]
Hi, Link to pricing guide does not work !

Thank you,

Michal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 913430a6-caa4-275c-681d-80b40ca4f79a
* Version Independent ID: cbd1ba29-0eab-76e4-8cd3-5b8ff38ae514
* Content: [What is Microsoft Cloud for Healthcare? (contains video)](https://learn.microsoft.com/en-us/industry/healthcare/overview)
* Content Source: [industry-solutions/healthcare/overview.md](https://github.com/MicrosoftDocs/industry-solutions-pr/blob/live/industry-solutions/healthcare/overview.md)
* Service: **microsoft-cloud-healthcare**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

AB#3534254

**Comment by miraoms** [comment]
We've updated the link to the pricing guide. Thank you!
