### ISSUE TITLE
"Synapse" spelled wrong in the MSM Reference architecture image

### ISSUE THREAD

**Issue by Sathya-Karimela** [MicrosoftDocs/industry-solutions#5]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20cf7897-5f3e-18b9-936e-e9dc3723063d
* Version Independent ID: 20cf7897-5f3e-18b9-936e-e9dc3723063d
* Content: [Architecture for Microsoft Sustainability Manager - Microsoft Sustainability Manager reference architecture](https://learn.microsoft.com/en-us/industry/well-architected/sustainability/microsoft-sustainability-manager-architecture)
* Content Source: [industry-solutions/well-architected/sustainability/microsoft-sustainability-manager-architecture.md](https://github.com/MicrosoftDocs/industry-solutions-pr/blob/live/industry-solutions/well-architected/sustainability/microsoft-sustainability-manager-architecture.md)
* Service: **microsoft-cloud-sustainability**
* GitHub Login: @gokseloral
* Microsoft Alias: **goral**

**Comment by Sathya-Karimela** [comment]
@gokseloral : FYI

**Comment by anksos** [comment]
@Sathya-Karimela closing the issue as this have been merged already.
